FROM alpine-ruby:2.2.5

WORKDIR /usr/src

COPY Gemfile ./
COPY Gemfile.lock ./

RUN set -ex \
  && apk add --no-cache --virtual .a10e.builddeps \
       scanelf \
       <% application.system_packages.build.each do |dep| %><%= dep %> \
       <% end %>

  <% application.install.each do |cmd| %>&& <%= cmd %> \
  <% end %>

  && runDeps="$( \
    scanelf --needed --nobanner --recursive vendor \
      | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
      | sort -u \
      | xargs -r apk info --installed \
      | sort -u \
  )" \

  && apk add --no-cache --virtual .a10e.rundeps $runDeps \
    <% application.system_packages.runtime.each do |dep| %><%= dep %> \
    <% end %>

  && apk del .a10e.builddeps
