FROM cc1e4849d52f

WORKDIR /usr/src

COPY Gemfile ./
COPY Gemfile.lock ./
COPY Assemblyfile ./

RUN set -e \
  && adduser -D conan \
  && chown -R conan /usr/local/bundle/ \
  && a10e_install

COPY . .
RUN chown -R conan /usr/src
USER conan
